# CI tests using GitHub Actions

name: CI

on:
  # trigger on push
  push:
    # to all branches
    branches:
      - '**'
    # ignore LICENSE, all .ignore and markdown files
    paths-ignore:
      - '*.md'
      - '*.ignore'
      - LICENSE
      - './images/*'
  pull_request:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      #/ Install Nextflow
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: GuillaumeFalourd/assert-command-line-output@v2
        with:
          command_line: nextflow run main.nf --some --invalid --paramzzz -bg | sed '1,2d;'
          assert_file_path: asserts/fail1.txt
          expected_result: PASSED
      
